[package]
name = "mc-playtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
eframe = "0.27.2"
egui = "0.27.2"
md5 = "0.7.0"
rfd = "0.14.1"
serde_json = "1.0.117"
